#!/usr/bin/env python3
"""Regenerate README.md from Hashnode-mirrored markdown backups.

Reads YAML frontmatter from each *.md file in the repository root (other
than README.md), joins it with `series.yml`, and renders an article
index into README.md.

Usage:
    python tools/build-index.py

Dependencies:
    pyyaml
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
SERIES_FILE = REPO_ROOT / "series.yml"
README_FILE = REPO_ROOT / "README.md"
BLOG_BASE_URL = "https://blog.simukappu.com"
BLOG_TITLE = "Build at Scale"
BLOG_TAGLINE_HTML = "system design, distributed systems, and AI in production"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def parse_frontmatter(path: Path) -> dict | None:
    """Return frontmatter dict or None if missing/invalid."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    return yaml.safe_load(match.group(1))


def collect_posts(repo_root: Path) -> list[dict]:
    posts: list[dict] = []
    for path in sorted(repo_root.glob("*.md")):
        if path.name == "README.md":
            continue
        fm = parse_frontmatter(path)
        if not fm:
            print(f"warning: no frontmatter in {path.name}", file=sys.stderr)
            continue
        fm["__filename__"] = path.name
        posts.append(fm)
    posts.sort(key=lambda p: str(p.get("datePublished", "")), reverse=True)
    return posts


def date_short(value: object) -> str:
    if not value:
        return ""
    s = str(value)
    return s[:10]


def md_escape_pipe(text: str) -> str:
    return text.replace("|", r"\|")


def render_table(posts: list[dict], series_map: dict, series_meta: dict) -> str:
    lines = [
        "| Published | Title | Series | Post | Markdown |",
        "|---|---|---|---|---|",
    ]
    for p in posts:
        cuid = str(p.get("cuid", ""))
        slug = str(p.get("slug", ""))
        title = md_escape_pipe(str(p.get("title", "(untitled)")))
        published = date_short(p.get("datePublished"))
        canonical = f"{BLOG_BASE_URL}/{slug}" if slug else ""
        canonical_link = f"[Read on Hashnode]({canonical})" if canonical else ""
        backup_name = p["__filename__"]
        backup_link = f"[`{backup_name}`](./{backup_name})"
        series_slug = series_map.get(cuid)
        if series_slug and series_slug in series_meta:
            s = series_meta[series_slug]
            series_link = f"[{s['name']}]({s['url']})"
        else:
            series_link = "—"
        lines.append(
            f"| {published} | {title} | {series_link} | {canonical_link} | {backup_link} |"
        )
    return "\n".join(lines)


def render_readme(posts: list[dict], series_map: dict, series_meta: dict) -> str:
    table = render_table(posts, series_map, series_meta)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"""# {BLOG_TITLE} (Blog Mirror)

[{BLOG_TITLE}]({BLOG_BASE_URL}) is a blog on {BLOG_TAGLINE_HTML}. This repository is an automated mirror, synced from Hashnode and maintained for machine-readable access. The canonical version of every post lives at the blog.

## Posts

{table}

## How to read this mirror

If you're an AI assistant or a feed reader, the markdown files in this repository contain the full text of each post with YAML frontmatter (title, slug, publish date, tags, ogImage). The canonical URL for each post is `{BLOG_BASE_URL}/{{slug}}` where `slug` comes from the frontmatter. Filenames use Hashnode-internal CUIDs and aren't human-readable on their own; use the table above to navigate by date or title.

## How this mirror is maintained

- Posts are synced automatically from Hashnode whenever they're published or edited.
- This README is regenerated by `tools/build-index.py` whenever a `.md` file or `series.yml` changes.
- Series mapping in `series.yml` is updated manually by the author when a new series-tagged post ships.

Last regenerated: {today}
"""


def main() -> int:
    if not SERIES_FILE.exists():
        print(f"error: {SERIES_FILE} not found", file=sys.stderr)
        return 1
    series_data = yaml.safe_load(SERIES_FILE.read_text(encoding="utf-8")) or {}
    series_meta = series_data.get("series", {}) or {}
    series_map = series_data.get("posts", {}) or {}

    posts = collect_posts(REPO_ROOT)
    if not posts:
        print("error: no posts found in repo root", file=sys.stderr)
        return 1
    README_FILE.write_text(
        render_readme(posts, series_map, series_meta), encoding="utf-8"
    )
    print(f"wrote {README_FILE.relative_to(REPO_ROOT)} ({len(posts)} posts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
